version: "3" 
services:
  # Web service layer
  nginx:
    image: nginx:1.17.3
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "90:90"
    depends_on:
      - php

  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
      - "./php/php-7.3.5/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - postgresql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
  
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /postgres/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /pgadmin-data:/var/lib/postgresql/data
    ports:
      - 80:80

volumes:
  db_data:
