version: "3.7" 
services:
  postgresql:
    image: postgres:12
    container_name: hr-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
     - ./postgres/data:/usr/local/pgsql/data
    networks:
      - hr-net
      - interna

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/storage/admin_root.com
    ports:
      - 8082:80
    networks:
      - hr-net
      - interna

volumes:
  db_data:

networks:
  hr-net:
    external: true
  interna:
