version: "3.7" 
services:
  postgresql:
    image: debezium/postgres:16-alpine
    container_name: hr-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
     - ./postgres/data:/usr/local/pgsql/data
     #- ./postgresqlCustom.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - hr-net
      - interna

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/storage
    ports:
      - 8082:80
    networks:
      - hr-net
      - interna

volumes:
  db_data:

networks:
  hr-net:
    external: true
  interna:
