version: "3" 
services:
  postgresql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
     - ./postgres/data:/usr/local/pgsql/data
    networks:
      - postgres-compose-network
      - hr-net

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/storage/admin_root.com
    ports:
      - 8082:80
    networks:
      - postgres-compose-network
      - hr-net

volumes:
  db_data:

networks: 
  postgres-compose-network:
    driver: bridge
  hr-net: 
    driver: bridge
